### ISSUE TITLE
能否实现直接调用本地终端软件打开命令窗口 , 不使用web Term

### ISSUE THREAD

**Issue by originnets** [mojocn/sshfortress#1]
能实现直接调用本地程序(crt , xshell 等软件)进行管理服务器吗?

**Comment by mojocn** [comment]
> 能实现直接调用本地程序(crt , xshell 等软件)进行管理服务器吗?

不知道这个是否是你需要的  [https://mojotv.cn/go/create-your-own-ssh-server](https://mojotv.cn/go/create-your-own-ssh-server)

还有一个类似的 https://github.com/libragen/felix 直接在命令行中快捷登陆ssh

这个功能我我只实现了一半
