### ISSUE TITLE
sshfortress和felix啥区别？都是大佬你的开源项目哇？

### ISSUE THREAD

**Issue by fenggolang** [mojocn/sshfortress#4]
问题1：https://github.com/libragen/felix 和 https://github.com/mojocn/sshfortress都是大佬的项目哇？

问题2：felix是命令行ssh登录，sshfortress借鉴了felix改用web ssh登录，我理解对不？

**Comment by mojocn** [comment]
是的
felix 可以生产 Gin Gorm RESTful CRUD 代码, 我的开发工具集
sshfortress 是在felix基础上完善web ui 功能, 可以记录ssh 命令日志 和 可以在网页是对管理的机器创建ssh账号,和收取.  felix 有命令行功能. 但是最windows/mac支持不好(不能使用terminal size 变化), web-ssh-terminal 可以解决窗口尺寸问题.

**Comment by cheyunhua** [comment]
可以开源sshfortress 的vue前端吗
