### ISSUE TITLE
添加ssh信息时，id_rsa的文本框只有1024个字符，无法填写完整

### ISSUE THREAD

**Issue by mmsoon** [mojocn/sshfortress#6]
我是用openssl生成的id_rsa, rsa2048，生成的文件有1796个字符，而两处ssh的key都只能输入1024个字符，导致无法成功。
```
ls -la ~/.ssh/id_rsa
-rw-------@ 1 xxx  staff  1796 Oct 18  2015 /Users/xxx/.ssh/id_rsa
```

建议将规格放大到2048，或更大一些。

**Comment by mojocn** [comment]
好的 我明天上班改一下

**Comment by mmsoon** [comment]
PrivateClound jumper那里还有一处需要修改。

**Comment by mojocn** [comment]
> PrivateClound jumper那里还有一处需要修改。

已经修复 非常感谢您的反馈

**Comment by mmsoon** [comment]
html这块代码好像不在里面，只好劳烦你改一下了。给力！
